Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,7 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      - name: Run Leapwork Automated Test flows, schedule Daily regression
+      - name: Run Leapwork Automated Test flows for multiple schedules
         shell: pwsh
         run: |
           # Define headers
@@ -18,111 +18,122 @@ jobs:
             "AccessKey" = "Qa56IlDnepCscGjY"
             "ngrok-skip-browser-warning" = "69488"
           }
-          
-          # Define API URL for starting schedule
-          $runScheduleId = "1b5c204b-37dc-47f1-b24b-84588728b56d"
-          $url = "https://1606-152-58-92-164.ngrok-free.app/api/v4/schedules/$runScheduleId/runNow"
-          
-          try {
-              # Make PUT request to start schedule
-              $response = Invoke-RestMethod -Uri $url -Method PUT -Headers $headers -ContentType "application/json" -ErrorAction Stop
-              Write-Output "Response: $($response | ConvertTo-Json -Depth 10)"
-              Write-Output "Response Status Code: $($response.StatusCode)"
-              # Check if starting schedule was successful
-              if ($true) {
-                  $jsonResponse = $response | ConvertTo-Json -Depth 10
-                  Write-Output "JSON Response: $jsonResponse"
-                  
-                  $runId = $response.RunId
-                  Write-Output "runId: $runId"
 
-                  # Store runId in an environment variable for subsequent steps
-                  echo "run_id=$runId" >> $env:GITHUB_ENV
+          # Fetch schedule IDs from the API
+          $scheduleApiUrl = "https://1606-152-58-92-164.ngrok-free.app/api/v4/schedules"
+          $schedulesResponse = Invoke-RestMethod -Uri $scheduleApiUrl -Method Get -Headers $headers -ContentType "application/json"
+          $scheduleIds = $schedulesResponse | ForEach-Object { $_.Id }
 
-                  # Initialize variables
-                  $timeDelay = 60  # Delay in seconds
-                  $isStillRunning = $true
-                  $runItemsId = @()
-                  $runItemsDetails = @()
+          # Initialize the CSV content
+          $csvContent = @("Flow Title,Passed Count,Failed Count")
 
-                  do {
-                      # Simulate waiting
-                      Write-Output "Waiting for $timeDelay seconds..."
-                      Start-Sleep -Seconds $timeDelay
+          foreach ($scheduleId in $scheduleIds) {
+            Write-Output "Processing Schedule ID: $scheduleId"
 
-                      # Make API call to retrieve executedRunItems
-                      $executedRunItems = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
-                      Write-Output "ExecutedRunItems: $($executedRunItems | ConvertTo-Json -Depth 10)"
-                      # Filter out already processed runItems
-                      $executedRunItems.RunItemIds = [string[]]$executedRunItems.RunItemIds
-                      $newExecutedRunItems = $executedRunItems.RunItemIds | Where-Object { $_ -notin $runItemsId }
-                      Write-Output "NewExecutedRunItems: $($newExecutedRunItems | ConvertTo-Json -Depth 10)"
-                      foreach ($runItemId in $newExecutedRunItems) {
-                          Write-Output "RunItemId: $runItemId"
-                          # Make API call to get runItem details
-                          $runItem = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/runItems/$runItemId" -Method Get -Headers $headers -ContentType "application/json"
+            # Define API URL for starting schedule
+            $url = "https://1606-152-58-92-164.ngrok-free.app/api/v4/schedules/$scheduleId/runNow"
 
-                          $status = $runItem.Status
-                          $flowTitle = $runItem.FlowInfo.FlowTitle
-                          
-                          Write-Output "Status: $status"
-                          Write-Output "Flow Title: $flowTitle"
-                          
-                          # Add runItem details to the list
-                          $runItemsDetails += [pscustomobject]@{
-                              'RunItemId' = $runItemId
-                              'FlowTitle' = $flowTitle
-                              'Status' = $status
-                          }
+            try {
+                # Make PUT request to start schedule
+                $response = Invoke-RestMethod -Uri $url -Method PUT -Headers $headers -ContentType "application/json" -ErrorAction Stop
+                Write-Output "Response: $($response | ConvertTo-Json -Depth 10)"
+                Write-Output "Response Status Code: $($response.StatusCode)"
+                # Check if starting schedule was successful
+                if ($true) {
+                    $jsonResponse = $response | ConvertTo-Json -Depth 10
+                    Write-Output "JSON Response: $jsonResponse"
 
-                          # Add runItemId to processed list
-                          $runItemsId += $runItemId
-                          Write-Output "Array of RunItems Id : $runItemsId"
-                      }
-          
-                      # Check if the runStatus is Finished
-                      Write-Output "RunId for RunStatus  : $runId"
-                      $runStatus = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/status" -Method Get -Headers $headers -ContentType "application/json"
-                      Write-Output "Run Status : $($runStatus.Status)"
-                      if ($($runStatus.Status) -eq "Finished") {
-                          # Check if all runItems have been processed
-                          $allExecutedRunItems = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
-                          Write-Output "All Executed Run Items: $($allExecutedRunItems | ConvertTo-Json -Depth 10)"
-                          Write-Output "All Executed Run Items Count: $($allExecutedRunItems.RunItemIds.Count)"
-                          Write-Output "Processed Run Items Count: $($runItemsId.Count)"
-                          if ($allExecutedRunItems.RunItemIds.Count -gt 0 -and $allExecutedRunItems.RunItemIds.Count -le $runItemsId.Count) {
-                              $isStillRunning = $false
-                          }
-                      }
+                    $runId = $response.RunId
+                    Write-Output "runId: $runId"
 
-                      if ($isStillRunning) {
-                          Write-Output "The schedule status is already '$runStatus' - wait a minute..."
-                      }
+                    # Store runId in an environment variable for subsequent steps
+                    echo "run_id=$runId" >> $env:GITHUB_ENV
 
-                  } while ($isStillRunning)
-                  # Prepare results for CSV
-                  $csvContent = @("Flow Title,Passed Count,Failed Count")
-                  $groupedRunItems = $runItemsDetails | Group-Object -Property FlowTitle
-                  foreach ($group in $groupedRunItems) {
-                      $flowTitle = $group.Name
-                      $passedCount = ($group.Group | Where-Object { $_.Status -eq 'Passed' }).Count
-                      $failedCount = ($group.Group | Where-Object { $_.Status -eq 'Failed' }).Count
-                      $csvContent += "$flowTitle,$passedCount,$failedCount"
-                  }
+                    # Initialize variables
+                    $timeDelay = 60  # Delay in seconds
+                    $isStillRunning = $true
+                    $runItemsId = @()
+                    $runItemsDetails = @()
 
-                  # Save CSV content to a file
-                  $csvContent | Out-File -FilePath output.csv -Encoding utf8
-                  Write-Output "Results saved to output.csv"
+                    do {
+                        # Simulate waiting
+                        Write-Output "Waiting for $timeDelay seconds..."
+                        Start-Sleep -Seconds $timeDelay
 
-              } else {
-                  Write-Error "Failed to start schedule. HTTP status code: $($response.StatusCode)"
-                  exit 1
-              }
+                        # Make API call to retrieve executedRunItems
+                        $executedRunItems = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
+                        Write-Output "ExecutedRunItems: $($executedRunItems | ConvertTo-Json -Depth 10)"
+                        # Filter out already processed runItems
+                        $executedRunItems.RunItemIds = [string[]]$executedRunItems.RunItemIds
+                        $newExecutedRunItems = $executedRunItems.RunItemIds | Where-Object { $_ -notin $runItemsId }
+                        Write-Output "NewExecutedRunItems: $($newExecutedRunItems | ConvertTo-Json -Depth 10)"
+                        foreach ($runItemId in $newExecutedRunItems) {
+                            Write-Output "RunItemId: $runItemId"
+                            # Make API call to get runItem details
+                            $runItem = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/runItems/$runItemId" -Method Get -Headers $headers -ContentType "application/json"
 
-          } catch {
-              Write-Error "Error occurred: $_"
-              exit 1
+                            $status = $runItem.Status
+                            $flowTitle = $runItem.FlowInfo.FlowTitle
+
+                            Write-Output "Status: $status"
+                            Write-Output "Flow Title: $flowTitle"
+
+                            # Add runItem details to the list
+                            $runItemsDetails += [pscustomobject]@{
+                                'RunItemId' = $runItemId
+                                'FlowTitle' = $flowTitle
+                                'Status' = $status
+                            }
+
+                            # Add runItemId to processed list
+                            $runItemsId += $runItemId
+                            Write-Output "Array of RunItems Id : $runItemsId"
+                        }
+
+                        # Check if the runStatus is Finished
+                        Write-Output "RunId for RunStatus  : $runId"
+                        $runStatus = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/status" -Method Get -Headers $headers -ContentType "application/json"
+                        Write-Output "Run Status : $($runStatus.Status)"
+                        if ($($runStatus.Status) -eq "Finished") {
+                            # Check if all runItems have been processed
+                            $allExecutedRunItems = Invoke-RestMethod -Uri "https://1606-152-58-92-164.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
+                            Write-Output "All Executed Run Items: $($allExecutedRunItems | ConvertTo-Json -Depth 10)"
+                            Write-Output "All Executed Run Items Count: $($allExecutedRunItems.RunItemIds.Count)"
+                            Write-Output "Processed Run Items Count: $($runItemsId.Count)"
+                            if ($allExecutedRunItems.RunItemIds.Count -gt 0 -and $allExecutedRunItems.RunItemIds.Count -le $runItemsId.Count) {
+                                $isStillRunning = $false
+                            }
+                        }
+
+                        if ($isStillRunning) {
+                            Write-Output "The schedule status is already '$runStatus' - wait a minute..."
+                        }
+
+                    } while ($isStillRunning)
+
+                    # Process results for current schedule
+                    $groupedRunItems = $runItemsDetails | Group-Object -Property FlowTitle
+                    foreach ($group in $groupedRunItems) {
+                        $flowTitle = $group.Name
+                        $passedCount = ($group.Group | Where-Object { $_.Status -eq 'Passed' }).Count
+                        $failedCount = ($group.Group | Where-Object { $_.Status -eq 'Failed' }).Count
+                        $csvContent += "$flowTitle,$passedCount,$failedCount"
+                    }
+
+                } else {
+                    Write-Error "Failed to start schedule. HTTP status code: $($response.StatusCode)"
+                    exit 1
+                }
+
+            } catch {
+                Write-Error "Error occurred: $_"
+                exit 1
+            }
           }
+
+          # Save CSV content to a file
+          $csvContent | Out-File -FilePath output.csv -Encoding utf8
+          Write-Output "Results saved to output.csv"
 
       - name: Upload output file
         uses: actions/upload-artifact@v3
